### ISSUE TITLE
Hard coded drive letters and install path

### ISSUE THREAD

**Issue by JohannesHoppe** [smonn/tfs-cmd#1]
I need that functionality and was happy to see your package.
Unfortunately I assume this to break because of the hard coded drive letters.

I would favour `%programfiles(x86)%` over `C:\Program Files (x86)\`.
I would favour `%programfiles%` over `C:\Program Files\`.

Additionally there are more environment-variables available:

`%VS110COMNTOOLS%` - Visual Studio 2012
`%VS120COMNTOOLS%` - Visual Studio 2013
`%VS140COMNTOOLS%` - Visual Studio 2015
see http://stackoverflow.com/a/6979543

So path to tf.exe can be also resolved to:
`%VS110COMNTOOLS%\..\IDE\tf`
`%VS120COMNTOOLS%\..\IDE\tf`
`%VS140COMNTOOLS%\..\IDE\tf`

**Comment by smonn** [comment]
Thanks @JohannesHoppe, good call. I've updated the paths to use the environment variables instead. I'm unable to test at this time (not running on Windows) so let me know if you run into issues with the update.
